# Generated by Django 5.1.7 on 2025-03-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweetmessage",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
