# Generated by Django 5.1.7 on 2025-03-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tc", "0002_alter_tweetmessage_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweetmessage",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
